site_name: Obsidian Notes (KYS)

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

nav:
  - Game Overview:
      - Details about the game: '_Game Overview/Details about the game.md'

  - Characters:
      - Character creation: 'Characters/Character creation.md'
      - Character descriptions: 'Characters/Character descriptions.md'
      - Ice Cream Man: 'Characters/Ice Cream Man.md'
      - John Officer: 'Characters/John Officer.md'
      - Main Character notes: 'Characters/Main Character notes.md'
      - Teacher: 'Characters/Teacher.md'

  - Code & Dev Notes:
      - Tutorial tasks:
          - Audio:
              - Ingame Voice lines (Text): 'Code & Dev Notes/Tutorial tasks/Audio/ingame Voice lines (Text).md'
              - Add voice lines: 'Code & Dev Notes/Tutorial tasks/Audio/tuto Add voice lines.md'

          - Design & Visuals:
              - Create dummy scenes: 'Code & Dev Notes/Tutorial tasks/Design & Visuals/Create dummy scenes for all scenes.md'
              - GUI: 'Code & Dev Notes/Tutorial tasks/Design & Visuals/GUI.md'
              - Evidence board mechanic: 'Code & Dev Notes/Tutorial tasks/Design & Visuals/tuto_evidence board mechanik und design.md'
              - Find a name for main character: 'Code & Dev Notes/Tutorial tasks/Design & Visuals/tuto_Find a name for the main character.md'
              - Graphics for lock picking: 'Code & Dev Notes/Tutorial tasks/Design & Visuals/tuto_graphics for the lock picking.md'
              - Key NPC design: 'Code & Dev Notes/Tutorial tasks/Design & Visuals/tuto_key npc design (teacher, icecream).md'
              - Main Character Animations: 'Code & Dev Notes/Tutorial tasks/Design & Visuals/tuto_Main Character Animations.md'
              - Main Character Design: 'Code & Dev Notes/Tutorial tasks/Design & Visuals/tuto_Main Character Design.md'

          - Inventory:
              - Inventory management: 'Code & Dev Notes/Tutorial tasks/Inventory/inventory management.md'
              - Design first item: 'Code & Dev Notes/Tutorial tasks/Inventory/tuto_design first item.md'
              - Integrate inventory: 'Code & Dev Notes/Tutorial tasks/Inventory/tuto_integrate_inventory.md'

          - Map:
              - Implement map navigation: 'Code & Dev Notes/Tutorial tasks/Map/tuto_implement_map_navigation.md'
              - Map design: 'Code & Dev Notes/Tutorial tasks/Map/tuto_map.md'

          - Misc:
              - Bugs & Fixes: 'Code & Dev Notes/Tutorial tasks/Misc/Bugs & Fixes.md'
              - Dev Notes: 'Code & Dev Notes/Tutorial tasks/Misc/Dev Notes.md'
              - Naming convention and structure: 'Code & Dev Notes/Tutorial tasks/Misc/Naming convention and File structure.md'

          - Scenes:
              - Forest Cabin: 'Code & Dev Notes/Tutorial tasks/Scenes/tuto_forest_cabin.md'
              - Forest Trail 01: 'Code & Dev Notes/Tutorial tasks/Scenes/tuto_forest_trail01.md'
              - Forest Trail 02: 'Code & Dev Notes/Tutorial tasks/Scenes/tuto_forest_trail02.md'
              - Ice Cream Shop: 'Code & Dev Notes/Tutorial tasks/Scenes/tuto_icecreamshop.md'
              - Office inside cabin: 'Code & Dev Notes/Tutorial tasks/Scenes/tuto_office inside cabin.md'
              - School: 'Code & Dev Notes/Tutorial tasks/Scenes/tuto_school.md'

          - System Features:
              - Implement main character: 'Code & Dev Notes/Tutorial tasks/System Features/tuto_implementierung vom Main character.md'
              - Integrate key NPCs: 'Code & Dev Notes/Tutorial tasks/System Features/tuto_integrate_key_npcs.md'
              - Interrogation mechanics: 'Code & Dev Notes/Tutorial tasks/System Features/tuto_interrogation mechanics.md'
              - Save/load functionality: 'Code & Dev Notes/Tutorial tasks/System Features/tuto_save_load_functionality.md'

  - Designs & Visuals:
      - Design description: 'Designs & Visuals/Design description.md'

  - Features:
      - Helpful commands: 'Features/Helpful commands.md'
      - LaTeX Math Support: 'Features/LaTeX Math Support.md'
      - Mermaid Diagrams: 'Features/Mermaid Diagrams.md'
      - Text Formatting: 'Features/Text Formatting.md'

  - Management & Planning:
      - Kanban Board notes:
          - Clarify how to embed an AI model (Agon): 'Management & Planning/Kanban Board notes/Clarify how to embed an AI model (Agon).md'
          - Improve the readme: 'Management & Planning/Kanban Board notes/Improve the readme.md'
          - README: 'Management & Planning/Kanban Board notes/README.md'
          - Set up a repository (Lukas): 'Management & Planning/Kanban Board notes/Set up a repository for the game (Lukas).md'
          - Tutorial Story Planning (Mareike): 'Management & Planning/Kanban Board notes/Write the tutorial story....md'
      - Meetings: 'Management & Planning/Meetings.md'
      - What if: 'Management & Planning/What if.md'
      - Backlog Kanban Board: 'Management & Planning/Backlog Kanban Board.md'

  - Music & SFX:
      - Inspiration: 'Music & SFX/Inspiration.md'
      - Notes: 'Music & SFX/Notes.md'
      - Songs & Sounds: 'Music & SFX/Songs & Sounds.md'

  - Story & Worldbuilding:
      - Tutorial Story Trials: 'Story & Worldbuilding/Tutorial Story Trials.md'
      - Tutorial Story Updated: 'Story & Worldbuilding/Tutorial Story Updated.md'
      - Tutorial Story Version 1: 'Story & Worldbuilding/Tutorial Story Version 1.md'

  - Technical Overview:
      - AI Notes: 'Technical Overview/AI Notes/index.md'
      - Tools & Resources: 'Technical Overview/Tools & Resources.md'
      - Comparison of Engines: 'Technical Overview/Comparison of Engines.md'
      - Technical details: 'Technical Overview/Technical details.md'

  - z All images:
      - Design: 'z All images/Design/index.md'
      - Main Character: 'z All images/Main Character/index.md'
      - Mechanics: 'z All images/Mechanics/index.md'
      - Npc: 'z All images/Npc/index.md'
      - Random: 'z All images/Random/index.md'
      - Scenes: 'z All images/Scenes/index.md'

  - z Fazit:
      - Agon: 'z Fazit/Agon/index.md'
      - Daniel: 'z Fazit/Daniel/index.md'
      - Lukas: 'z Fazit/Lukas/index.md'
      - Mareike: 'z Fazit/Mareike/index.md'
      - Pierre: 'z Fazit/Pierre/index.md'
